# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
lang: en-US
title: Guillaume Sérazin
email: g.serazin@unsw.edu.au
description: "My public website about me and my research activities"
baseurl:
url: https://serazing.github.io
author:
  name: Guillaume Sérazin
  github: serazing
  flickr: Blé noir
  picture:
address:
  - line: Clinate Change Research Centre
  - line: 14, Avenue Édouarb Belin 31400 Toulouse
github_username: serazing
flickr_username: Blé noir
copyright:
logo: https://www.ccrc.unsw.edu.au/sites/default/files/upload/ccrc-logo.jpg

remote_theme: mmistakes/jekyll-theme-basically-basic

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-scholar
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Front Matter Defaults
defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      read_time: true

# Bibliography settings
scholar:
  style: american-meteorological-society
  locale: en

  sort_by: year
  order: descending

  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: bib

  replace_strings: true
  join_strings:    true

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"